name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 8.3.0
  connectivity_plus: 6.0.4
  equatable: 2.0.5
  freezed_annotation: 2.4.4
  get_it: 7.7.0
  injectable: 2.4.4
  internet_connection_checker: 1.0.0+1
  json_annotation: 4.9.0
  rxdart: 0.28.0
  synchronized: 3.1.0+1
  url_launcher: 6.3.0
  flutter_screenutil: ^5.9.3
  flash: ^3.1.1
  envied: ^1.1.1

dev_dependencies:
  auto_route_generator: 8.0.0
  build_runner: 2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  very_good_analysis: 5.1.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
